name: recommender_discord_bot
channels:
  - conda-forge
  - defaults
dependencies:
  - numpy=1.26.2
  - openssl=3.3.1
  - pandas=2.1.4
  - pip=23.3.1
  - python=3.12.0
  - scikit-surprise=1.1.3
  - scipy=1.11.4
  - pip:
      - setuptools==80.9.0
      - aiohttp==3.9.1
      - aiosqlite==0.19.0
      - discord.py==2.3.2
      - fuzzywuzzy==0.18.0
      - python-dotenv==1.0.0
      - python-levenshtein==0.23.0
      - scikit-learn==1.3.2
      - openai==1.78.1
